version: '3'
include:
  - ./config/docker-compose/companies/compose.yaml
  - ./config/docker-compose/users/compose.yaml
services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:2-watch
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
      - ./krakend/graphql/:/graphql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [ "start-dev", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
