version: "3.8"
include:
  - ./companies/compose.yaml
  - ./offers/compose.yaml
services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:2-watch
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    ports:
      - "8080:8080"
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
      - ./krakend/graphql/:/graphql
