version: '3'
services:
  companies-api:
    image: seasonist/companies:1.0.0
    build:
      context: ../../../companies/
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - companies-db
    ports:
      - "127.0.0.1:8082:8080"

  companies-db:
    image: postgres:16
    environment:
      POSTGRES_USER: companies-svc
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_DB: companies
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U companies-svc -d companies" ]
      interval: 5s
      timeout: 5s
      retries: 6
#    ports:
#      - "127.0.0.1:5432:5432"
    volumes:
      - companies_db_data:/var/lib/postgresql/data

volumes:
  companies_db_data:
