version: '3'
services:
  offers-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - offers_data:/var/lib/postgresql/data

  offers-api:
    image: seasonist/offers:1.0.0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "8082:8080"

volumes:
  offers_data:
