version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: users-svc
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_DB: users
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [ "start-dev", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ../config/keycloak:/opt/keycloak/data/import

volumes:
  postgres_data:
