version: '3'
services:
  users-api:
    image: seasonist/users:1.0.0
    build:
      context: ../../../users/
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - users-db
    ports:
      - "127.0.0.1:8083:8080"

  users-db:
    image: postgres:16
    environment:
      POSTGRES_USER: users-svc
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_DB: users
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U users-svc -d users" ]
      interval: 5s
      timeout: 5s
      retries: 6
#    ports:
#      - "127.0.0.1:5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

volumes:
  users_db_data:
