name: Lint

on:
  push:

jobs:
  run-linter:
    name: Run Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
      - run: npm ci
      - run: npm run lint
